### ISSUE TITLE
dockerfile for model generation

### ISSUE THREAD

**Issue by fdiblen** [ADAH-EviDENce/evidence#57]
- [x] create a ``model-generation/Dockerfile`` which mounts ``experiments/your_experiment`` to ``/data``
- [x] It should read the data from ``/data/corpus``
- [x] add an entrypoint script to
   - [ ] run preprocessing notebook (unattended)
   - [ ] run model generation notebook (unattended)
- [x] the output should be written to ``/data``

**Comment by sverhoeven** [comment]
Use docker-compose for running the the model generation container, this will hide the mounts and uid/gid in the compose file.

With the model generation service in the main docker-compose.yml, it will always run during `up` subcommand, so we only should generate when there is no doc2vec.json. Alternatively use `up server` instead of `up` to exclude generator.

**Comment by fdiblen** [comment]
- The model is generated by using a Docker image. The docker image and the scripts are in [/model-generation/](/model-generation/) folder.

- Jupyter notebooks are executed without any user input in this [script](https://github.com/ADAH-EviDENce/WorkingTitleCloseReader/blob/8cf8c38c26392ccc5962c33168a66fdd91bacc5b/model-generation/run.sh).

- The output is saved to the docker bind mounts:
  - ``${PWD}/model-generation/notebooks:/data/notebooks``
  - ``${PWD}/experiments/${EXPERIMENT}/corpus:/data/corpus``
  - ``${PWD}/experiments/${EXPERIMENT}/model:/data/model``
